version: "3"
services:
  postgres:
    build:
      context: .
    image: postgres:latest
    container_name: "hubba-db" 
    environment:
      POSTGRES_DB: "hubba"
      POSTGRES_USER: "hubba"
      POSTGRES_PASSWORD: "hubba" 
      PGDATA: "/data/hubba"
    volumes:
       - hubba-db:/data/hubba
    networks:
       - hubba-subnet 
    ports:
      - "5432:5432"
    restart: unless-stopped
  user-service:
      build:
        context: ./user-service
        dockerfile: ./Dockerfile
      image: "user-service"
      container_name: "user-service"
      environment:
        DB_HOSTNAME: "hubba-db"
        DB_USER: "hubba"
        DB_PASSWORD: "hubba" 
        DB_PORT: 5432
        DB_NAME: "hubba-user"
        VERSION: "DEV"
        PROJECT_ID: hubba-412704
        USER_EVENT_SUBSCRIPTION_ID: dev-user-event
        EVENTS_EVENT_SUBSCRIPTION_ID: dev-events-event
        ORGANIZATIONS_EVENT_SUBSCRIPTION_ID: dev-organizations-event
        USER_EVENT_TOPIC_ID: dev-user-event
        EVENTS_EVENT_TOPIC_ID: dev-events-event
        ORGANIZATIONS_EVENT_TOPIC_ID: dev-organizations-event
      networks:
         - hubba-subnet
      ports:
        - "8000:8000"
      restart: unless-stopped
  events-service:
      build:
        context: ./events-service
        dockerfile: ./Dockerfile
      image: "events-service"
      container_name: "events-service"
      environment:
        DB_HOSTNAME: "hubba-db"
        DB_USER: "hubba"
        DB_PASSWORD: "hubba" 
        DB_PORT: 5432
        DB_NAME: "hubba-events"
        VERSION: "DEV"
        PROJECT_ID: hubba-412704
        USER_EVENT_SUBSCRIPTION_ID: dev-user-event
        EVENTS_EVENT_SUBSCRIPTION_ID: dev-events-event
        ORGANIZATIONS_EVENT_SUBSCRIPTION_ID: dev-organizations-event
        USER_EVENT_TOPIC_ID: dev-user-event
        EVENTS_EVENT_TOPIC_ID: dev-events-event
        ORGANIZATIONS_EVENT_TOPIC_ID: dev-organizations-event
      networks:
         - hubba-subnet
      ports:
        - "8001:8001"
      restart: unless-stopped
  organizations-service:
      build:
        context: ./organizations-service
        dockerfile: ./Dockerfile
      image: "organizations-service"
      container_name: "organizations-service"
      environment:
        DB_HOSTNAME: "hubba-db"
        DB_USER: "hubba"
        DB_PASSWORD: "hubba" 
        DB_PORT: 5432
        DB_NAME: "hubba-organizations"
        VERSION: "DEV"
        PROJECT_ID: hubba-412704
        USER_EVENT_SUBSCRIPTION_ID: dev-user-event
        EVENTS_EVENT_SUBSCRIPTION_ID: dev-events-event
        ORGANIZATIONS_EVENT_SUBSCRIPTION_ID: dev-organizations-event
        USER_EVENT_TOPIC_ID: dev-user-event
        EVENTS_EVENT_TOPIC_ID: dev-events-event
        ORGANIZATIONS_EVENT_TOPIC_ID: dev-organizations-event
      networks:
         - hubba-subnet
      ports:
        - "8002:8002"
      restart: unless-stopped
  web-service:
      build:
        context: ./web-service
        dockerfile: ./Dockerfile
      image: "web-service"
      container_name: "web-service"
      environment:
        USER_SERVICE_HOSTNAME: "user-service"
        USER_SERVICE_PORT: 8000
      networks:
         - hubba-subnet
      ports:
        - "80:80"
      restart: unless-stopped

volumes:
  hubba-db:
    external: true
networks:
  hubba-subnet:
