import defaultimg from '@/assets/images/defaultimg.png';
export const getUserOrgs = async () => {
    const data = {
        orgs: [
            {
                id: 'org1',
                name: 'org1',
                image: 'https://via.placeholder.com/250',
                description: 'org1 description',
                owner: 'org1 owner',
                moderators: ['mod1', 'mod2'],
                users: [
                    {
                        id: 'user_1',
                        username: 'user1',
                        email: 'email1',
                        profile_image: defaultimg,
                        bio: 'bio1',
                        followers: ['follower1', 'follower2'],
                        num_followers: 2,
                        following: ['following1', 'following2'],
                        num_following: 2,
                        streaming_status: 1,
                        channel_url: 'https://www.google.com',
                        stream_url: 'stream_url1',
                        video_urls: ['video_url1', 'video_url2'],
                        joined_event_ids: ['event1', 'event2'],
                        past_event_ids: ['event3', 'event4'],
                        joined_orgs: ['org1', 'org2'],
                        platforms: ['platform1', 'platform2'],
                    },
                    {
                        id: 'user_2',
                        username: 'user2',
                        email: 'email2',
                        profile_image: defaultimg,
                        bio: 'bio2',
                        followers: ['follower1', 'follower2'],
                        num_followers: 2,
                        following: ['following1', 'following2'],
                        num_following: 2,
                        streaming_status: 1,
                        channel_url: 'https://www.google.com',
                        stream_url: 'stream_url2',
                        video_urls: ['video_url1', 'video_url2'],
                        joined_event_ids: ['event1', 'event2'],
                        past_event_ids: ['event3', 'event4'],
                        joined_orgs: ['org1', 'org2'],
                        platforms: ['platform1', 'platform2'],
                    },
                ],
                events: ['event1', 'event2'],
            },
            {
                id: 'org2',
                name: 'org2',
                image: 'https://via.placeholder.com/250',
                description: 'org2 description',
                owner: 'org2 owner',
                moderators: ['mod1', 'mod2'],
                users: [
                    {
                        id: 'user_1',
                        username: 'user1',
                        email: 'email1',
                        profile_image: defaultimg,
                        bio: 'bio1',
                        followers: ['follower1', 'follower2'],
                        num_followers: 2,
                        following: ['following1', 'following2'],
                        num_following: 2,
                        streaming_status: 1,
                        channel_url: 'https://www.google.com',
                        stream_url: 'stream_url1',
                        video_urls: ['video_url1', 'video_url2'],
                        joined_event_ids: ['event1', 'event2'],
                        past_event_ids: ['event3', 'event4'],
                        joined_orgs: ['org1', 'org2'],
                        platforms: ['platform1', 'platform2'],
                    },
                    {
                        id: 'user_2',
                        username: 'user2',
                        email: 'email2',
                        profile_image: defaultimg,
                        bio: 'bio2',
                        followers: ['follower1', 'follower2'],
                        num_followers: 2,
                        following: ['following1', 'following2'],
                        num_following: 2,
                        streaming_status: 1,
                        channel_url: 'https://www.google.com',
                        stream_url: 'stream_url2',
                        video_urls: ['video_url1', 'video_url2'],
                        joined_event_ids: ['event1', 'event2'],
                        past_event_ids: ['event3', 'event4'],
                        joined_orgs: ['org1', 'org2'],
                        platforms: ['platform1', 'platform2'],
                    },
                ],
                events: ['event1', 'event2'],
            },
        ],
    };
    return data;
};

export const getOrg = async (id: string) => {
    const data = {
        id: id,
        name: `org ${id}`,
        image: 'https://via.placeholder.com/250',
        description: 'org1 description. \n join us at https://www.google.com!',
        owner: 'org1 owner',
        moderators: ['mod1', 'mod2'],
        users: [
            {
                id: 'user_1',
                username: 'user1',
                email: 'email1',
                profile_image: defaultimg,
                bio: 'bio1',
                followers: ['follower1', 'follower2'],
                num_followers: 2,
                following: ['following1', 'following2'],
                num_following: 2,
                streaming_status: 1,
                channel_url: 'https://www.google.com',
                stream_url: 'stream_url1',
                video_urls: ['video_url1', 'video_url2'],
                joined_event_ids: ['event1', 'event2'],
                past_event_ids: ['event3', 'event4'],
                joined_orgs: ['org1', 'org2'],
                platforms: ['platform1', 'platform2'],
            },
            {
                id: 'user_2',
                username: 'user2',
                email: 'email2',
                profile_image: defaultimg,
                bio: 'bio2',
                followers: ['follower1', 'follower2'],
                num_followers: 2,
                following: ['following1', 'following2'],
                num_following: 2,
                streaming_status: 1,
                channel_url: 'https://www.google.com',
                stream_url: 'stream_url2',
                video_urls: ['video_url1', 'video_url2'],
                joined_event_ids: ['event1', 'event2'],
                past_event_ids: ['event3', 'event4'],
                joined_orgs: ['org1', 'org2'],
                platforms: ['platform1', 'platform2'],
            },
            {
                id: 'id1',
                username: 'Jackey',
                email: 'jackey@jackey.com',
                profile_image: defaultimg,
                bio: 'bio3',
                followers: ['follower1', 'follower2'],
                num_followers: 2,
                following: ['following1', 'following2'],
                num_following: 2,
                streaming_status: 1,
                channel_url: 'https://www.google.com',
                stream_url: 'stream_url3',
                video_urls: ['video_url1', 'video_url2'],
                joined_event_ids: ['event1', 'event2'],
                past_event_ids: ['event3', 'event4'],
                joined_orgs: ['org1', 'org2'],
                platforms: ['platform1', 'platform2'],
            },
        ],
        events: ['event1', 'event2'],
    };
    return data;
};
