name: build-and-deploy

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
  
env:
  GKE_CLUSTER: hubba-cluster     # Add your cluster name here.
  GKE_ZONE: us-central1          # Add your cluster zone here.
  TIMESTAMP: latest

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      TIMESTAMP: ${{ steps.set-time.outputs.TIMESTAMP }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Current Date as Env Variable
        run: echo "TIMESTAMP=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_ENV

      - id: set-time
        name: Set Output Timestamp
        run: echo "TIMESTAMP=${{ env.TIMESTAMP }}" >> "$GITHUB_OUTPUT"

      - name: Pass Timestamp to Deploy Stage
        id: pass-ts
        run: |
          echo "::set-output name=TIMESTAMP::$TIMESTAMP"

  # build-push-webservice:
  #   runs-on: ubuntu-latest
  #   needs: [setup]

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
        
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Setup .env.local File
  #       env:
  #         FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
  #       run: |
  #         touch .env.local
  #         echo $FIREBASE_CONFIG >> .env.local
  #       working-directory: web-service
  #       shell: bash

  #     - name: Use Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '20.x'
  #     - run: |
  #         npm install
  #         npm run lint
  #         npm run build
  #       working-directory: web-service

  #     - name: Build and Push web-service
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: web-service
  #         platforms: linux/amd64
  #         push: true
  #         tags: eddisonso/web-service:${{needs.setup.outputs.TIMESTAMP}}, eddisonso/web-service:latest

  build-push-userservice:
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup firebase-sa-cred.json File
        env:
          FIREBASE_SA_CRED: ${{ secrets.FIREBASE_SA_CRED }}
        run: |
          touch firebase-sa-cred.json
          echo $FIREBASE_SA_CRED >> firebase-sa-cred.json
        working-directory: user-service
        shell: bash
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push user-service
        uses: docker/build-push-action@v5
        with:
          build-args: |
            DB_USER=${{ secrets.DB_USER }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME="user-db"
            DB_HOSTNAME=${{ secrets.DB_HOSTNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            PROJECT_ID=${{ secrets.PROJECT_ID }}
            USER_EVENT_SUBSCRIPTION_ID=${{ secrets.USER_EVENT_SUBSCRIPTION_ID }}
            EVENTS_EVENT_SUBSCRIPTION_ID=${{ secrets.EVENTS_EVENT_SUBSCRIPTION_ID }}
            USER_EVENT_TOPIC_ID=${{ secrets.USER_EVENT_TOPIC_ID }}
            EVENTS_EVENT_TOPIC_ID=${{ secrets.EVENTS_EVENT_TOPIC_ID }}
            ORGANIZATIONS_EVENT_TOPIC_ID=${{ secrets.ORGANIZATIONS_EVENT_TOPIC_ID }}
            SERVICE_ACCOUNT=${{ secrets.SERVICE_ACCOUNT }}
            VERSION=${{needs.setup.outputs.TIMESTAMP}}
          context: user-service
          platforms: linux/amd64
          push: true
          tags: eddisonso/user-service:${{needs.setup.outputs.TIMESTAMP}}, eddisonso/user-service:latest

  build-push-eventsservice:
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup firebase-sa-cred.json File
        env:
          FIREBASE_SA_CRED: ${{ secrets.FIREBASE_SA_CRED }}
        run: |
          touch firebase-sa-cred.json
          echo $FIREBASE_SA_CRED >> firebase-sa-cred.json
        working-directory: events-service
        shell: bash
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push events-service
        uses: docker/build-push-action@v5
        with:
          build-args: |
            DB_USER=${{ secrets.DB_USER }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME="events-db"
            DB_HOSTNAME=${{ secrets.DB_HOSTNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            PROJECT_ID=${{ secrets.PROJECT_ID }}
            USER_EVENT_SUBSCRIPTION_ID=${{ secrets.USER_EVENT_SUBSCRIPTION_ID }}
            EVENTS_EVENT_SUBSCRIPTION_ID=${{ secrets.EVENTS_EVENT_SUBSCRIPTION_ID }}
            USER_EVENT_TOPIC_ID=${{ secrets.USER_EVENT_TOPIC_ID }}
            EVENTS_EVENT_TOPIC_ID=${{ secrets.EVENTS_EVENT_TOPIC_ID }}
            ORGANIZATIONS_EVENT_TOPIC_ID=${{ secrets.ORGANIZATIONS_EVENT_TOPIC_ID }}
            SERVICE_ACCOUNT=${{ secrets.SERVICE_ACCOUNT }}
            VERSION=${{needs.setup.outputs.TIMESTAMP}}
          context: events-service
          platforms: linux/amd64
          push: true
          tags: eddisonso/events-service:${{needs.setup.outputs.TIMESTAMP}}, eddisonso/events-service:latest
  
  build-push-organizationsservice:
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup firebase-sa-cred.json File
        env:
          FIREBASE_SA_CRED: ${{ secrets.FIREBASE_SA_CRED }}
        run: |
          touch firebase-sa-cred.json
          echo $FIREBASE_SA_CRED >> firebase-sa-cred.json
        working-directory: organizations-service
        shell: bash
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push organizations-service
        uses: docker/build-push-action@v5
        with:
          build-args: |
            DB_USER=${{ secrets.DB_USER }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME="organizations-db"
            DB_HOSTNAME=${{ secrets.DB_HOSTNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            PROJECT_ID=${{ secrets.PROJECT_ID }}
            USER_EVENT_SUBSCRIPTION_ID=${{ secrets.USER_EVENT_SUBSCRIPTION_ID }}
            EVENTS_EVENT_SUBSCRIPTION_ID=${{ secrets.EVENTS_EVENT_SUBSCRIPTION_ID }}
            USER_EVENT_TOPIC_ID=${{ secrets.USER_EVENT_TOPIC_ID }}
            EVENTS_EVENT_TOPIC_ID=${{ secrets.EVENTS_EVENT_TOPIC_ID }}
            ORGANIZATIONS_EVENT_TOPIC_ID=${{ secrets.ORGANIZATIONS_EVENT_TOPIC_ID }}
            SERVICE_ACCOUNT=${{ secrets.SERVICE_ACCOUNT }}
            VERSION=${{needs.setup.outputs.TIMESTAMP}}
          context: organizations-service
          platforms: linux/amd64
          push: true
          tags: eddisonso/organizations-service:${{needs.setup.outputs.TIMESTAMP}}, eddisonso/organizations-service:latest

  build-push-fileservice:
    runs-on: ubuntu-latest
    needs: [setup]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup firebase-sa-cred.json File
        env:
          FIREBASE_SA_CRED: ${{ secrets.FIREBASE_SA_CRED }}
        run: |
          touch firebase-sa-cred.json
          echo $FIREBASE_SA_CRED >> firebase-sa-cred.json
        working-directory: file-service
        shell: bash
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push file-service
        uses: docker/build-push-action@v5
        with:
          build-args: |
            BUCKET_SERVICE_ACCOUNT=${{ secrets.BUCKET_SERVICE_ACCOUNT }}
          context: file-service
          platforms: linux/amd64
          push: true
          tags: eddisonso/file-service:${{needs.setup.outputs.TIMESTAMP}}, eddisonso/file-service:latest
      
  deploy:
    runs-on: ubuntu-latest
    needs: [build-push-userservice, build-push-eventsservice, build-push-organizationsservice, build-push-fileservice, setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - id: "auth"
        name: "authenticate with google cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"
  
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
  
      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: "hubba-419505"
  
      - name: Deploy
        run: |-
          kubectl set image deployment/user-service user-service=eddisonso/user-service:${{needs.setup.outputs.TIMESTAMP}}
          # kubectl set image deployment/web-service web-service=eddisonso/web-service:${{needs.setup.outputs.TIMESTAMP}}
          kubectl set image deployment/events-service events-service=eddisonso/events-service:${{needs.setup.outputs.TIMESTAMP}}
          kubectl set image deployment/organizations-service organizations-service=eddisonso/organizations-service:${{needs.setup.outputs.TIMESTAMP}}
          kubectl set image deployment/file-service file-service=eddisonso/file-service:${{needs.setup.outputs.TIMESTAMP}}

  seed:
    runs-on: ubuntu-latest
    needs: ["deploy", "setup"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup firebase-sa-cred.json File
        env:
          FIREBASE_SA_CRED: ${{ secrets.FIREBASE_SA_CRED }}
        run: |
          touch firebase-sa-cred.json
          echo $FIREBASE_SA_CRED >> firebase-sa-cred.json
        working-directory: utils/seeder
        shell: bash

      - name: Seed
        working-directory: utils/seeder
        run: |-
          docker build --build-arg api_key=${{ secrets.api_key }} --build-arg VERSION=${{ needs.setup.outputs.TIMESTAMP }} -t seeder .
          docker run seeder
