name: Draft PR

on:
  issues:
    types: [opened]

jobs:
  create-draft-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GitHub CLI
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.8'

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Configure GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh auth setup-git

      - name: Branch from Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          BRANCH_NAME="issue-${ISSUE_NUMBER}"
          git checkout -b $BRANCH_NAME

      - name: Fetch Issue Details
        id: issue_details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          ISSUE_TITLE=$(gh issue view $ISSUE_NUMBER --json title -q .title)
          ISSUE_BODY=$(gh issue view $ISSUE_NUMBER --json body -q .body)
          echo "::set-output name=TITLE::$ISSUE_TITLE"
          echo "::set-output name=BODY::$(echo "$ISSUE_BODY" | sed 's/$/%0A/')"

      - name: Create Draft Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ steps.issue_details.outputs.TITLE }}
          ISSUE_BODY: ${{ steps.issue_details.outputs.BODY }}
          BRANCH_NAME: issue-${{ github.event.issue.number }}
        run: |
          gh pr create --draft --title "${ISSUE_TITLE}" --body "This is an automated draft PR for issue #${ISSUE_NUMBER}\n\nLink to issue: #${ISSUE_NUMBER}\n\nOriginal issue details:\n${ISSUE_BODY}" --base main --head $BRANCH_NAME

